### ISSUE TITLE
Hidden files are not candidates

### ISSUE THREAD

**Issue by yuki-yano** [tzachar/cmp-fuzzy-path#4]
Setting `options = { 'fd', '--hidden', '--max-depth', '20', '--full-path', '--exclude', '.git' }` does not make files starting with dot candidates.
For example, `.github` or `.eslintrc`.

If the command is executed directly, it will be included in the result.

**Comment by tzachar** [comment]
You need to add `-H` to `fd`

**Comment by tzachar** [comment]
![1](https://user-images.githubusercontent.com/4946827/187060233-7d625f64-7979-4992-87cc-1892afc6e2cd.png)

**Comment by yuki-yano** [comment]
`--hidden` works the same as `-H` but is not a candidate in my environment.
I can see that it is included in the results of the command execution, but is there a better way to debug the plugin?

**Comment by tzachar** [comment]
> `--hidden` works the same as `-H` but is not a candidate in my environment. 

What do you mean here? what is 'not a candidate'?

> I can see that it is included in the results of the command execution, but is there a better way to debug the plugin?

On my end, as you can see in the picture, it is included in the results and appears as a completion option.

As for debugging, for now you can add `print`s....

**Comment by yuki-yano** [comment]
Sorry for my poor English.
Attached is an image of the command run and the completion result.

`fd --max-depth 20 --full-path --hidden --exclude .git` outputs `.bar`, but it does not appear in the completion candidates in the vim.

The two Vim's in the lower right corner are what happens when you type `b` and `.b`, respectively.
The Vim on the upper right gives `foo` as a candidate when you type `f`.

The following options are passed to fuzzy_path, but it doesn't make any difference if you don't pass them.

```
options = {
  fd_cmd = {
    'fd',
    '--hidden',
    '--max-depth',
    '20',
    '--full-path',
    '--exclude',
    '.git',
  },
},
```

![CleanShot 2022-08-30 at 16 18 02](https://user-images.githubusercontent.com/5423775/187375365-9092dc01-f364-4e09-960a-24273d751473.png)

**Comment by tzachar** [comment]
I am using the same setup as you, and I do get `.bar` when typing `:e b`
This is my machine; 
```
❯ fd --version
fd 8.3.2
❯ uname -a
Linux vault-group.com 5.15.0-46-generic #49-Ubuntu SMP Thu Aug 4 18:03:25 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
❯ cat /etc/issue
Ubuntu 22.04.1 LTS \n \l
❯ nvim --version
NVIM v0.8.0-dev-969-g7a9b59379
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

On which platform are you?

**Comment by yuki-yano** [comment]
I found the problem.
The `options` in the README is correct `option`.

```diff
diff --git a/README.md b/README.md
index 6d4801b..83ae30b 100644
--- a/README.md
+++ b/README.md
@@ -60,7 +60,7 @@ Configuration can be passed when configuring `cmp`:
 ```lua
 cmp.setup.cmdline(':', {
   sources = cmp.config.sources({
-    { name = 'fuzzy_path', options = {fd_timeout_msec = 1500} }
+    { name = 'fuzzy_path', option = {fd_timeout_msec = 1500} }
   })
 })
 ```

**Comment by yuki-yano** [comment]
By passing `option` I was able to get the completion as expected.
Thanks for checking!

```
{
  name = 'fuzzy_path',
  trigger_characters = { ' ', '.', '/', '~' },
  option = {
    fd_cmd = {
      'fd',
      '--hidden',
      '--max-depth',
      '20',
      '--full-path',
      '--exclude',
      '.git',
    },
  },
},
```

**Comment by tzachar** [comment]
Good catch.
I pushed a commit so the plugin would use `options`, as is documented.
10x.
